// packages/svelte/src/SpirographAnimated.svelte
<script lang="ts">
  // Animated + controllable Spirograph canvas, written with Svelte 5 runes.
  // The public prop is named `state`; it is aliased to `pattern` so the `$state` rune is not
  // ambiguous with a `state` binding (see SpirographCanvas.svelte).
  import { onDestroy } from 'svelte';
  import type { SpirographState } from '@spirograph/core';
  import { DrawAnimation } from '@spirograph/anim';
  import { CanvasRenderer, exportPng, exportSvg } from '@spirograph/canvas';
  import type { CanvasRenderer as CanvasRendererType } from '@spirograph/canvas';
  import type { SpirographAnimationControl, PlayMode } from './types.js';

  interface Props {
    state: SpirographState;
    playMode?: PlayMode;
    baseDurationMs?: number;
    segmentsPerSecond?: number;
    onDone?: () => void;
    control?: SpirographAnimationControl | undefined;
    className?: string;
    style?: string;
    id?: string;
  }

  let {
    state: pattern,
    playMode = 'sequential',
    baseDurationMs,
    segmentsPerSecond = 350,
    onDone,
    control = undefined,
    className = '',
    style = '',
    id = undefined,
  }: Props = $props();

  let canvas = $state<HTMLCanvasElement>();
  let renderer: CanvasRendererType | null = null;
  let ro: ResizeObserver | null = null;
  let anim: DrawAnimation | null = null;
  let wired = false;

  function renderStatic(): void {
    renderer?.renderStatic(pattern);
  }

  function computeDuration(): number {
    if (baseDurationMs) return baseDurationMs;
    const items = renderer ? renderer.items(pattern) : [];
    const totalSegs = items.reduce((n: number, i) => n + (i.curve.count - 1), 0);
    return Math.max(1000, (totalSegs / segmentsPerSecond) * 1000);
  }

  function stopAnimation(): void {
    if (anim) {
      anim.stop();
      anim = null;
    }
  }

  function play(): void {
    if (!renderer) return;
    if (anim && anim.isRunning) {
      if (anim.isPaused) anim.resume();
      return;
    }
    const next = new DrawAnimation(
      (progress: number) => renderer!.renderProgress(pattern, playMode, progress),
      () => {
        anim = null;
        onDone?.();
        renderer?.renderStatic(pattern);
      },
      computeDuration(),
    );
    next.setSpeed(pattern.speed);
    anim = next;
    next.start();
  }

  function pause(): void {
    if (anim && anim.isRunning && !anim.isPaused) anim.pause();
  }

  function resume(): void {
    if (anim && anim.isRunning && anim.isPaused) anim.resume();
  }

  function setSpeed(speed: number): void {
    anim?.setSpeed(speed);
  }

  function wireControl(): void {
    if (wired || !control) return;
    wired = true;
    control.exportPng = (size = 2048, filename = 'spirograph.png') => {
      if (renderer) exportPng(renderer.items(pattern), pattern.background, size, filename);
    };
    control.exportSvg = (size = 2048, filename = 'spirograph.svg') => {
      if (renderer) exportSvg(renderer.items(pattern), pattern.background, size, filename);
    };
    control.play = play;
    control.pause = pause;
    control.resume = resume;
    control.stop = stopAnimation;
    control.setSpeed = setSpeed;
  }

  // After the canvas binds, and whenever the pattern changes: (re)create the renderer,
  // stop any running animation, and redraw the static pattern.
  $effect(() => {
    if (!canvas) return;
    if (!renderer) {
      renderer = new CanvasRenderer(canvas);
      ro = new ResizeObserver(() => renderStatic());
      ro.observe(canvas);
      wireControl();
    }
    stopAnimation();
    renderStatic();
  });

  onDestroy(() => {
    stopAnimation();
    ro?.disconnect();
    ro = null;
    renderer = null;
  });
</script>

<canvas
  bind:this={canvas}
  {id}
  class={className}
  style={"width:100%;height:100%;display:block;" + style}
></canvas>

// packages/react-native/src/SpirographAnimated.tsx
import React, { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import type { SpirographAnimatedProps, SpirographAnimationHandle } from './types.js';
import { useRenderData, computeGearDrawParams } from './useRenderData.js';
import { SvgRenderer } from './SvgRenderer.js';
import { SvgGearRenderer } from './SvgGearRenderer.js';
import { DrawAnimation } from '@spirograph/anim';

/**
 * Animated + controllable Spirograph SVG. Draws the finished pattern by default;
 * the ref handle exposes play/pause/resume/stop/setSpeed for a simulated drawing
 * animation (backed by @spirograph/anim's DrawAnimation).
 *
 * When `state` changes while the animation is running, the animation stops and the
 * static pattern is redrawn.
 */
export const SpirographAnimated = React.forwardRef<
  SpirographAnimationHandle,
  SpirographAnimatedProps
>(function SpirographAnimated(
  {
    state,
    size,
    showGears = false,
    playMode = 'sequential',
    baseDurationMs,
    segmentsPerSecond = 350,
    onDone,
    onPlayingChange,
    testID,
  },
  ref,
) {
  // Animation progress: 1 = fully drawn static render.
  const [progress, setProgress] = useState(1);
  const animRef = useRef<DrawAnimation | null>(null);

  // Keep latest props in refs so the animation callbacks see current values.
  const onDoneRef = useRef(onDone);
  onDoneRef.current = onDone;
  const onPlayingChangeRef = useRef(onPlayingChange);
  onPlayingChangeRef.current = onPlayingChange;

  // Current render data + item geometry for the current progress.
  const result = useRenderData(state, size.width, size.height, progress, playMode);
  const gearParams = useMemo(
    () => computeGearDrawParams(result.items, progress, playMode),
    [result.items, progress, playMode],
  );

  const computeDuration = useCallback((): number => {
    if (baseDurationMs) return baseDurationMs;
    const totalSegs = result.items.reduce((n, i) => n + (i.curve.count - 1), 0);
    return Math.max(1000, (totalSegs / segmentsPerSecond) * 1000);
  }, [baseDurationMs, segmentsPerSecond, result.items]);

  const notifyPlaying = useCallback((playing: boolean) => {
    onPlayingChangeRef.current?.(playing);
  }, []);

  const stopDraw = useCallback(() => {
    const anim = animRef.current;
    if (anim) {
      anim.stop();
      animRef.current = null;
    }
    setProgress(1);
    notifyPlaying(false);
  }, [notifyPlaying]);

  const play = useCallback(() => {
    const anim = animRef.current;
    if (anim && anim.isRunning) {
      if (anim.isPaused) {
        anim.resume();
        notifyPlaying(true);
      }
      return;
    }
    const duration = computeDuration();
    const next = new DrawAnimation(
      (p: number) => setProgress(p),
      () => {
        animRef.current = null;
        notifyPlaying(false);
        setProgress(1);
        onDoneRef.current?.();
      },
      duration,
    );
    next.setSpeed(state.speed);
    animRef.current = next;
    next.start();
    notifyPlaying(true);
  }, [computeDuration, notifyPlaying, state.speed]);

  const pause = useCallback(() => {
    const anim = animRef.current;
    if (anim && anim.isRunning && !anim.isPaused) anim.pause();
  }, []);

  const resume = useCallback(() => {
    const anim = animRef.current;
    if (anim && anim.isRunning && anim.isPaused) anim.resume();
  }, []);

  const setSpeed = useCallback((speed: number) => {
    animRef.current?.setSpeed(speed);
  }, []);

  React.useImperativeHandle(
    ref,
    () => ({ play, pause, resume, stop: stopDraw, setSpeed }),
    [play, pause, resume, stopDraw, setSpeed],
  );

  // Stop the animation + redraw static whenever the state object changes.
  useEffect(() => {
    stopDraw();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state]);

  // Unmount cleanup.
  useEffect(() => {
    return () => {
      animRef.current?.stop();
      animRef.current = null;
    };
  }, []);

  return (
    <SvgRenderer
      renderData={result.renderData}
      width={size.width}
      height={size.height}
      background={state.background}
      testID={testID}
    >
      {showGears && result.items.length > 0 && (
        <SvgGearRenderer
          state={state}
          transform={result.transform}
          gearAngle={gearParams.gearAngle}
          activePenIndex={gearParams.activePenIndex}
        />
      )}
    </SvgRenderer>
  );
});
