// src/demos/svelte/AnimatedDemo.svelte
<script lang="ts">
  import type { SpirographState } from '@spirograph/core';
  import { SpirographAnimated } from '@spirograph/svelte';
  import type { SpirographAnimationControl, PlayMode } from '@spirograph/svelte';
  import { applyPatch, buildDemoState, randomize } from '../state.js';
  import DemoCard from './DemoCard.svelte';
  import DemoControls from './DemoControls.svelte';

  let state: SpirographState = $state(buildDemoState());
  let control: SpirographAnimationControl = $state({});
  let playMode: PlayMode = $state('sequential');
  let gears = $state(false);

  function patch(p: Partial<SpirographState>) {
    state = applyPatch(state, p);
  }
  function random() {
    state = randomize(state);
  }
  function toggleGears() {
    gears = !gears;
    state = applyPatch(state, { showGears: gears });
  }
</script>

<DemoCard title="Animated & controllable" tag="&lt;SpirographAnimated&gt;">
  {#snippet stage()}
    <SpirographAnimated {state} {control} playMode={playMode} />
  {/snippet}

  {#snippet toolbar()}
    <button class="demo-action" onclick={() => control.play?.()}>
      <i class="fa-solid fa-play"></i> Play
    </button>
    <button class="demo-action" onclick={() => control.pause?.()}>
      <i class="fa-solid fa-pause"></i> Pause
    </button>
    <button class="demo-action" onclick={() => control.resume?.()}>
      <i class="fa-solid fa-forward"></i> Resume
    </button>
    <button class="demo-action" onclick={() => control.stop?.()}>
      <i class="fa-solid fa-stop"></i> Stop
    </button>
    <button class="demo-action" onclick={() => control.setSpeed?.(0.5)}>0.5×</button>
    <button class="demo-action" onclick={() => control.setSpeed?.(1)}>1×</button>
    <button class="demo-action" onclick={() => control.setSpeed?.(2)}>2×</button>
    <span style="flex:1"></span>
    <button class="demo-action {gears ? 'active' : ''}" onclick={toggleGears}>
      <i class="fa-solid fa-gear"></i> Gears
    </button>
    <button
      class="demo-action {playMode === 'simultaneous' ? 'active' : ''}"
      onclick={() => {
        playMode = playMode === 'sequential' ? 'simultaneous' : 'sequential';
      }}
    >
      {playMode === 'sequential' ? 'One pen' : 'All pens'}
    </button>
  {/snippet}

  {#snippet controls()}
    <DemoControls {state} onPatch={patch} onRandom={random} />
  {/snippet}
</DemoCard>

// src/demos/react/AnimatedDemo.tsx
import { useRef, useState } from 'react';
import type { SpirographState } from '@spirograph/core';
import { SpirographAnimated } from '@spirograph/react';
import type { SpirographAnimationHandle, PlayMode } from '@spirograph/react';
import { applyPatch, buildDemoState, randomize } from '../state';
import { DemoCard } from './DemoCard';
import { DemoControls } from './DemoControls';

export function AnimatedDemo() {
  const [state, setState] = useState<SpirographState>(() => buildDemoState());
  const [playMode, setPlayMode] = useState<PlayMode>('sequential');
  const [gears, setGears] = useState(false);
  const ref = useRef<SpirographAnimationHandle>(null);

  const patch = (p: Partial<SpirographState>) => setState((s) => applyPatch(s, p));
  const random = () => setState((s) => randomize(s));
  const toggleGears = () => {
    setGears((g) => {
      const next = !g;
      setState((s) => applyPatch(s, { showGears: next }));
      return next;
    });
  };
  const togglePlayMode = () => setPlayMode((m) => (m === 'sequential' ? 'simultaneous' : 'sequential'));

  return (
    <DemoCard
      title="Animated & controllable"
      tag="&lt;SpirographAnimated&gt;"
      stage={
        <div className="demo-stage">
          <SpirographAnimated ref={ref} state={state} playMode={playMode} />
        </div>
      }
      toolbar={
        <>
          <button className="demo-action" onClick={() => ref.current?.play()}>
            <i className="fa-solid fa-play" /> Play
          </button>
          <button className="demo-action" onClick={() => ref.current?.pause()}>
            <i className="fa-solid fa-pause" /> Pause
          </button>
          <button className="demo-action" onClick={() => ref.current?.resume()}>
            <i className="fa-solid fa-forward" /> Resume
          </button>
          <button className="demo-action" onClick={() => ref.current?.stop()}>
            <i className="fa-solid fa-stop" /> Stop
          </button>
          <button className="demo-action" onClick={() => ref.current?.setSpeed(0.5)}>0.5×</button>
          <button className="demo-action" onClick={() => ref.current?.setSpeed(1)}>1×</button>
          <button className="demo-action" onClick={() => ref.current?.setSpeed(2)}>2×</button>
          <span style={{ flex: 1 }} />
          <button className={'demo-action' + (gears ? ' active' : '')} onClick={toggleGears}>
            <i className="fa-solid fa-gear" /> Gears
          </button>
          <button className={'demo-action' + (playMode === 'simultaneous' ? ' active' : '')} onClick={togglePlayMode}>
            {playMode === 'sequential' ? 'One pen' : 'All pens'}
          </button>
        </>
      }
      controls={<DemoControls state={state} onPatch={patch} onRandom={random} />}
    />
  );
}
