// src/demos/react/DemoCard.tsx
import type { ReactNode } from 'react';

interface Props {
  title: string;
  tag?: string;
  stage: ReactNode;
  toolbar?: ReactNode;
  controls?: ReactNode;
}

export function DemoCard({ title, tag, stage, toolbar, controls }: Props) {
  return (
    <div className="demo-card">
      <div className="demo-card-head">
        <span>{title}</span>
        {tag && <span className="tag">{tag}</span>}
      </div>
      <div className="demo-stage">{stage}</div>
      {toolbar && <div className="demo-toolbar">{toolbar}</div>}
      {controls}
    </div>
  );
}

// src/demos/svelte/DemoCard.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    title: string;
    tag?: string;
    stage: Snippet;
    toolbar?: Snippet;
    controls?: Snippet;
  }

  let { title, tag = '', stage, toolbar, controls }: Props = $props();
</script>

<div class="demo-card">
  <div class="demo-card-head">
    <span>{title}</span>
    {#if tag}
      <span class="tag">{tag}</span>
    {/if}
  </div>
  <div class="demo-stage">
    {@render stage()}
  </div>
  {#if toolbar}
    {@render toolbar()}
  {/if}
  {#if controls}
    {@render controls()}
  {/if}
</div>
